### PR TITLE
formatting

### PR DESCRIPTION
**Pull request by tymondesigns**
Hi Harry, sorry if i'm being annoying with these small PR's :P

### CODE REVIEW

**Comment by florianbouvot** [comment]
The comment formatting is intentional, `//` hide comment from the compiled CSS file. So first part of your PR is not needed.

@csswizardry use the same formatting for comments in settings and tools layers.

**Comment by tymondesigns** [comment]
@florianbouvot fair enough. Although all comments wil be ultimately removed when using `--style compressed`. But I suppose it would be useful when debugging

**Comment by csswizardry** [comment]
It’s basically just: http://cssguidelin.es/#preprocessor-comments :)

**Comment by tymondesigns** [comment]
yep makes sense. thanks Harry :+1:

**Pull request closed without merging**
